ALTER TABLE EMPRESA ADD EMP_TIPO VARCHAR(10) DEFAULT 'FILIAL';
ALTER TABLE EMPRESA ADD EMP_MATRIZ_ID INTEGER;
ALTER TABLE EMPRESA ADD CONSTRAINT FK_EMP_MATRIZ FOREIGN KEY (EMP_MATRIZ_ID) REFERENCES EMPRESA(EMP_ID);

CREATE TABLE CLIENTES (
    CLI_EMP_ID INTEGER NOT NULL REFERENCES EMPRESA(EMP_ID),
    CLI_CODIGO INTEGER NOT NULL,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_CELULAR VARCHAR(20),
    CLI_EMAIL VARCHAR(100),
    CLI_CIDADE VARCHAR(50),
    CLI_UF VARCHAR(2),
    CLI_CNPJ_CPF VARCHAR(18),
    CLI_SITUACAO VARCHAR(15),
    CLI_LIMITE NUMERIC(9,2),
    CLI_BAIRRO VARCHAR(30),
    CLI_CEP VARCHAR(10),
    CLI_DATAU TIMESTAMP,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (CLI_EMP_ID, CLI_CODIGO)
);

CREATE TABLE PRODUTOS (
    PRO_EMP_ID INTEGER NOT NULL REFERENCES EMPRESA(EMP_ID),
    PRO_CODIGO INTEGER NOT NULL,
    PRO_NOME VARCHAR(200) NOT NULL,
    PRO_DESCRICAO VARCHAR(100),
    PRO_FABRICANTE VARCHAR(50),
    PRO_CODBARRA VARCHAR(30),
    PRO_QUANTIDADE NUMERIC(9,2),
    PRO_VALORV NUMERIC(9,4),
    PRO_VALORC NUMERIC(9,4),
    PRO_GRU INTEGER,
    PRO_ESTADO VARCHAR(8),
    PRO_GTIN VARCHAR(14),
    PRO_DATAUA DATE,
    CONSTRAINT PK_PRODUTOS PRIMARY KEY (PRO_EMP_ID, PRO_CODIGO)
);

CREATE TABLE VENDAS (
    VEN_EMP_ID INTEGER NOT NULL REFERENCES EMPRESA(EMP_ID),
    VEN_CODIGO INTEGER NOT NULL,
    VEN_DATA DATE,
    VEN_VALOR NUMERIC(9,2),
    VEN_HORA TIME,
    VEN_FUN INTEGER,
    VEN_CLI INTEGER,
    VEN_VENDEDOR INTEGER,
    VEN_NF INTEGER,
    VEN_DATAC DATE,
    CONSTRAINT PK_VENDAS PRIMARY KEY (VEN_EMP_ID, VEN_CODIGO)
);

CREATE TABLE MOVIMENTACOES (
    MOV_EMP_ID INTEGER NOT NULL REFERENCES EMPRESA(EMP_ID),
    MOV_CODIGO INTEGER NOT NULL,
    MOV_DESCRICAO VARCHAR(100),
    MOV_NOME VARCHAR(50),
    MOV_DATA DATE,
    MOV_DEBITO NUMERIC(9,2),
    MOV_CREDITO NUMERIC(9,2),
    MOV_TIPO INTEGER,
    MOV_DATAHORA TIMESTAMP,
    CONSTRAINT PK_MOVIMENTACOES PRIMARY KEY (MOV_EMP_ID, MOV_CODIGO)
);

CREATE TABLE RECEBIMENTOS (
    REC_EMP_ID INTEGER NOT NULL REFERENCES EMPRESA(EMP_ID),
    REC_CODIGO INTEGER NOT NULL,
    REC_VALOR NUMERIC(9,2),
    REC_DUPLICATA VARCHAR(30),
    REC_OBS VARCHAR(100),
    REC_VENCIMENTO DATE,
    REC_DATAR DATE,
    REC_SITUACAO SMALLINT,
    CONSTRAINT PK_RECEBIMENTOS PRIMARY KEY (REC_EMP_ID, REC_CODIGO)
);

CREATE TABLE ORDENS (
    ORD_EMP_ID INTEGER NOT NULL REFERENCES EMPRESA(EMP_ID),
    ORD_CODIGO INTEGER NOT NULL,
    ORD_DATA DATE,
    ORD_VALOR NUMERIC(9,2),
    ORD_HORA TIME,
    ORD_FUN INTEGER,
    ORD_CLI INTEGER,
    ORD_OBS VARCHAR(300),
    ORD_ESTADO VARCHAR(15),
    ORD_DATAPRONTO DATE,
    ORD_DATAENTREGA DATE,
    ORD_VEICULO VARCHAR(30),
    ORD_PLACA VARCHAR(10),
    CONSTRAINT PK_ORDENS PRIMARY KEY (ORD_EMP_ID, ORD_CODIGO)
);

CREATE TABLE GRUPO_1 (
    G1_CODIGO INTEGER NOT NULL,
    G1_NOME VARCHAR(30),
    CONSTRAINT PK_GRUPO_1 PRIMARY KEY (G1_CODIGO)
);

CREATE TABLE GRUPOS (
    GRU_CODIGO INTEGER NOT NULL,
    GRU_NOME VARCHAR(20),
    GRU_G1 INTEGER REFERENCES GRUPO_1(G1_CODIGO),
    CONSTRAINT PK_GRUPOS PRIMARY KEY (GRU_CODIGO)
);

CREATE TABLE TAMANHOS (
    TAM_CODIGO INTEGER NOT NULL,
    TAM_PRO INTEGER,
    TAM_TAMANHO VARCHAR(25),
    TAM_SIGLA VARCHAR(2),
    TAM_VALOR NUMERIC(9,4),
    CONSTRAINT PK_TAMANHOS PRIMARY KEY (TAM_CODIGO)
);

CREATE TABLE GRADES (
    GRA_CODIGO INTEGER NOT NULL,
    GRA_PRO INTEGER,
    GRA_VALOR NUMERIC(9,2),
    GRA_TAM INTEGER REFERENCES TAMANHOS(TAM_CODIGO),
    GRA_QUANTIDADE NUMERIC(9,2),
    GRA_CODBARRA VARCHAR(30),
    GRA_COR VARCHAR(30),
    CONSTRAINT PK_GRADES PRIMARY KEY (GRA_CODIGO)
);

CREATE TABLE TRANSFERENCIA (
    TR_ID INTEGER NOT NULL,
    TR_MATRIZ_ID INTEGER NOT NULL REFERENCES EMPRESA(EMP_ID),
    TR_FILIAL_ID INTEGER NOT NULL REFERENCES EMPRESA(EMP_ID),
    TR_DATA DATE NOT NULL,
    TR_STATUS VARCHAR(15) NOT NULL,
    TR_OBS VARCHAR(250),
    CONSTRAINT PK_TRANSFERENCIA PRIMARY KEY (TR_ID)
);

CREATE TABLE TRANSFERENCIA_ITEM (
    TRI_ID INTEGER NOT NULL,
    TRI_TR_ID INTEGER NOT NULL REFERENCES TRANSFERENCIA(TR_ID),
    TRI_PRO_CODIGO INTEGER NOT NULL,
    TRI_QUANTIDADE NUMERIC(9,2) NOT NULL,
    TRI_VALOR NUMERIC(9,4) NOT NULL,
    CONSTRAINT PK_TRANSFERENCIA_ITEM PRIMARY KEY (TRI_ID)
);

CREATE GENERATOR GEN_TRANSFERENCIA_ID;
CREATE GENERATOR GEN_TRANSFERENCIA_ITEM_ID;

SET TERM ^ ;

CREATE TRIGGER BI_TRANSFERENCIA_ID FOR TRANSFERENCIA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.TR_ID IS NULL) THEN
        NEW.TR_ID = GEN_ID(GEN_TRANSFERENCIA_ID, 1);
END^

CREATE TRIGGER BI_TRANSFERENCIA_ITEM_ID FOR TRANSFERENCIA_ITEM
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.TRI_ID IS NULL) THEN
        NEW.TRI_ID = GEN_ID(GEN_TRANSFERENCIA_ITEM_ID, 1);
END^

SET TERM ; ^
